[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "pyoad"
version = "0.0.2"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.10"',
]
